stepify stepify-merged: A/B via native push

diff --git a/.github/workflows/review-release.yml b/.github/workflows/review-release.yml
--- a/.github/workflows/review-release.yml
+++ b/.github/workflows/review-release.yml
@@ -1,134 +1,85 @@
 name: SmallRye Pre Release
-
 on:
-  pull_request:
-    paths:
-      - '.github/project.yml'
-
+  push: null
 jobs:
   release:
     runs-on: ubuntu-latest
     name: pre release
-
     steps:
-      - uses: radcortez/project-metadata-action@main
-        name: retrieve project metadata
-        id: metadata
-        with:
-          github-token: ${{secrets.GITHUB_TOKEN}}
-          metadata-file-path: '.github/project.yml'
+    - uses: radcortez/project-metadata-action@main
+      name: retrieve project metadata
+      id: metadata
+      with:
+        github-token: ${{secrets.GITHUB_TOKEN}}
+        metadata-file-path: .github/project.yml
+    - name: Validate version
+      if: contains(steps.metadata.outputs.current-version, 'SNAPSHOT')
+      run: 'echo ''::error::Cannot release a SNAPSHOT version.''
 
-      - name: Validate version
-        if: contains(steps.metadata.outputs.current-version, 'SNAPSHOT')
-        run: |
-          echo '::error::Cannot release a SNAPSHOT version.'
-          exit 1
+        exit 1
 
-      - uses: radcortez/milestone-review-action@main
-        name: milestone review
-        with:
-          github-token: ${{secrets.GITHUB_TOKEN}}
-          milestone-title: ${{steps.metadata.outputs.current-version}}
-
+        '
+    - uses: radcortez/milestone-review-action@main
+      name: milestone review
+      with:
+        github-token: ${{secrets.GITHUB_TOKEN}}
+        milestone-title: ${{steps.metadata.outputs.current-version}}
   integration-build-smallrye-health:
     runs-on: ubuntu-latest
-    name: Integration - Build SmallRye Health
     if: contains(github.event.pull_request.body, 'Breaking change') == false
     outputs:
       SNAPSHOT_VERSION: ${{ steps.version-step.outputs.SNAPSHOT_VERSION }}
-
     steps:
-      - uses: actions/checkout@v2
+    - uses: actions/checkout@v2
+    - uses: actions/setup-java@v4
+      with:
+        java-version: 17
+        distribution: temurin
+        cache: maven
+    - name: Build with Maven
+      run: mvn -B javadoc:javadoc formatter:validate install
+    - id: version-step
+      name: Save version for integration builds
+      run: 'VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args=''${project.version}'' --non-recursive
+        exec:exec)
 
-      - uses: actions/setup-java@v4
-        with:
-          java-version: 17
-          distribution: temurin
-          cache: maven
+        echo "::set-output name=SNAPSHOT_VERSION::$VERSION"
 
-      - name: Build with Maven
-        run: mvn -B javadoc:javadoc formatter:validate install
+        '
+    - uses: actions/checkout@v2
+      name: Checkout Quarkus
+      with:
+        repository: quarkusio/quarkus
+    - name: Quarkus integration
+      env:
+        SNAPSHOT_VERSION: ${{ steps.version-step.outputs.SNAPSHOT_VERSION }}
+      run: './mvnw -Dquickly -Dsmallrye-health.version="$SNAPSHOT_VERSION"
 
-      - id: version-step
-        name: Save version for integration builds
-        run: |
-          VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
-          echo "::set-output name=SNAPSHOT_VERSION::$VERSION"
+        ./mvnw clean verify -pl extensions/smallrye-health/deployment -Dsmallrye-health.version="$SNAPSHOT_VERSION"
 
-      - uses: actions/upload-artifact@v4
-        with:
-          name: smallrye-health
-          path: ~/.m2/repository/io/smallrye
+        ./mvnw clean verify -pl tcks/microprofile-health -Dtcks -Dsmallrye-health.version="$SNAPSHOT_VERSION"
 
-  integration-verification-quarkus:
-    runs-on: ubuntu-latest
-    name: Integration verification for Quarkus
-    if: contains(github.event.pull_request.body, 'Breaking change') == false
-    needs: integration-build-smallrye-health
+        '
+    - uses: actions/checkout@v2
+      name: Checkout WildFly
+      with:
+        repository: wildfly/wildfly
+      if: '!cancelled() && steps.version-step.conclusion == ''success'''
+    - name: WildFly integration
+      env:
+        SNAPSHOT_VERSION: ${{ steps.version-step.outputs.SNAPSHOT_VERSION }}
+      run: './mvnw clean install -DallTests -DskipTests -DskipITs -Denforcer.skip -Dversion.io.smallrye.smallrye-health="$SNAPSHOT_VERSION"
 
-    steps:
-      - uses: actions/checkout@v2
+        ./mvnw clean verify -pl microprofile/health-smallrye -Dversion.io.smallrye.smallrye-health="$SNAPSHOT_VERSION"
 
-      - uses: actions/download-artifact@v4
-        with:
-          name: smallrye-health
-          path: ~/.m2/repository/io/smallrye
+        ./mvnw clean verify -pl testsuite/integration/microprofile -Dts.standalone.microprofile -Dtest="org.wildfly.test.integration.microprofile.health.*TestCase"
+        -Dversion.io.smallrye.smallrye-health="$SNAPSHOT_VERSION"
 
-      - uses: actions/setup-java@v4
-        with:
-          java-version: 17
-          distribution: temurin
-          cache: maven
+        ./mvnw clean verify -pl testsuite/integration/microprofile-tck/health -Dts.standalone.microprofile
+        -Dversion.io.smallrye.smallrye-health="$SNAPSHOT_VERSION"
 
-      - uses: actions/checkout@v2
-        name: Checkout Quarkus
-        with:
-          repository: quarkusio/quarkus
+        ./mvnw clean verify -pl testsuite/integration/manualmode-expansion -DallTests -Dtest="org.wildfly.test.manual.microprofile.health.*TestCase"
+        -Dversion.io.smallrye.smallrye-health="$SNAPSHOT_VERSION"
 
-      - name: Quarkus integration
-        env:
-          SNAPSHOT_VERSION: ${{ needs.integration-build-smallrye-health.outputs.SNAPSHOT_VERSION }}
-        run: |
-          ./mvnw -Dquickly -Dsmallrye-health.version="$SNAPSHOT_VERSION"
-          ./mvnw clean verify -pl extensions/smallrye-health/deployment -Dsmallrye-health.version="$SNAPSHOT_VERSION"
-          ./mvnw clean verify -pl tcks/microprofile-health -Dtcks -Dsmallrye-health.version="$SNAPSHOT_VERSION"
-
-  integration-verification-wildfly:
-    runs-on: ubuntu-latest
-    name: Integration verification for WildFly
-    if: contains(github.event.pull_request.body, 'Breaking change') == false
-    needs: integration-build-smallrye-health
-
-    steps:
-      - uses: actions/checkout@v2
-
-      - uses: actions/download-artifact@v4
-        with:
-          name: smallrye-health
-          path: ~/.m2/repository/io/smallrye
-
-      - uses: actions/setup-java@v4
-        with:
-          java-version: 17
-          distribution: temurin
-          cache: maven
-
-      - uses: actions/checkout@v2
-        name: Checkout WildFly
-        with:
-          repository: wildfly/wildfly
-
-      - name: WildFly integration
-        env:
-          SNAPSHOT_VERSION: ${{ needs.integration-build-smallrye-health.outputs.SNAPSHOT_VERSION }}
-        run: |
-          ./mvnw clean install -DallTests -DskipTests -DskipITs -Denforcer.skip -Dversion.io.smallrye.smallrye-health="$SNAPSHOT_VERSION"
-          ./mvnw clean verify -pl microprofile/health-smallrye -Dversion.io.smallrye.smallrye-health="$SNAPSHOT_VERSION"
-          ./mvnw clean verify -pl testsuite/integration/microprofile -Dts.standalone.microprofile -Dtest="org.wildfly.test.integration.microprofile.health.*TestCase" -Dversion.io.smallrye.smallrye-health="$SNAPSHOT_VERSION"
-          ./mvnw clean verify -pl testsuite/integration/microprofile-tck/health -Dts.standalone.microprofile -Dversion.io.smallrye.smallrye-health="$SNAPSHOT_VERSION"
-          ./mvnw clean verify -pl testsuite/integration/manualmode-expansion -DallTests -Dtest="org.wildfly.test.manual.microprofile.health.*TestCase" -Dversion.io.smallrye.smallrye-health="$SNAPSHOT_VERSION"
-
-
-
-          
-          
+        '
+      if: '!cancelled() && steps.version-step.conclusion == ''success'''
